### ISSUE TITLE
Need to be able to allow users to store observations

### ISSUE THREAD

**Issue by stringfellow** [openwater/h2o-really#2]
At the moment, there is no way to add observations.

These should be allowed via a form that encourages the user to fill out as many fields as possible.

The fields will be 'schema-free' in that they are stored in hstore, but each top level key should be the parameter that they are measuring, so we also need to define those parameters.

Each measurement will have a level of accuracy (e.g. "presence/absence", "n decimal places"… ) a value ("present", "absent", "between 10 and 20 ppb"…) and a kit type ("watermax 9000", "GS/MS Cambridge lab"… )

**Comment by stringfellow** [comment]
It turns out that (I didn't read enough) hstore doesn't do more than 1 level deep as everything has to be text.

To work around this, each observations should be like this:

```
{
  "Nitrates": XXX
}
```

where XXX is a jsonified version of the attributes of the observation, e.g.:

```
{
  'max': 30,
  'min': 20,
  'unit': 'mg NO3/l',
  'description': 'High',
  'classification': 'Environment Agency GQA',
}
```

Or similar. I guess the keys in that JSON will be defined by the classification system used. So, in this case we have min/max because that is what the GQA uses. For users adding measurements from home test kits, they would have to add these themselves (which might get really annoying? but unlikely that one user will be going round testing everything, so maybe distributed load is ok?) Consistency will have to be enforced at entry point.

**Comment by jimr** [comment]
Might it be worth switching to just use the native JSON support in Postgres? We can fudge it by stringifying the nested dicts on the way in and parsing them on the way out, but pure JSON would be neater (unless there's a benefit / reason I'm missing).

**Comment by stringfellow** [comment]
Hum, well, my reasoning was that by using hstore, you could then make native queries, so for example to get all measurements that have a "nitrates" key. I'm not sure of the extent of pgsql's JSON support - does it allow you to query on the JSON?

**Comment by jimr** [comment]
Not yet, but it's coming in 9.3 (which is due to be released soon). Are you sure we can't just break out observations into a separate model & add relationships? The structure of them seems reasonably fixed, and we can always add a 'annotations' hstore / JSON field where the schema doesn't quite fit. Maybe I'm missing something (I'm not very familiar with the data).

As for allowing people to add observations, we can switch that on in the API really easily. Not sure about the rest of the UI. Either way, it'll need documenting I suppose :)

**Comment by stringfellow** [comment]
The problem with it being fixed-schema is that there are just so many different types of measurement - some are ranges, some are colorimetric, some are really high precision… maybe we can add models for all of these things but it just seemed to make more sense to not have fixed schema and instead provide guidance keys (so, when testing for Phoshate with the La Motte 5982 colorimetric TesTab kit, the fields provided would be 'value' and automatically filled would be 'unit=ppm' … and so on) - the benefit is that we can loosely define a lot of different kits/tests and even though they may not be cross-comparable, an analyst who knows what all the values mean will just be able to query for e.g. "All Nitrates recordings in 1km of SomePoint" and they'll get all sorts - but they'll get all the metadata about each measurement, and can break it up as needed.

**Comment by stringfellow** [comment]
Possibly what is emerging from this is a new model called 'Test' that has an hstore with all this stuff in it, and the user then just selects the Test and adds the value to their Measurement… If they need a new Test, then they can add that… ?

**Comment by jimr** [comment]
That would seem to make sense aye. I've been looking at hooking up API filters and without ORM/db supported query we will end up doing it in python which is going to be super slow.

**Comment by stringfellow** [comment]
Hmmmmmm ok. I think I have a fear of making the interface for users to add new things, is partly why I like the idea of a catch-all… but that is not a good reason.

**Comment by stringfellow** [comment]
Ok - think I've got something that will work, will push later hopefully.

**Comment by jimr** [comment]
Sweet.

**Comment by stringfellow** [comment]
Deployed this so its all a bit better. Realised I did a stupid server-restart level database query on the parameter picker for maps though, in that change… still, not bad!

**Comment by stringfellow** [comment]
Woooooo finally…
