### ISSUE TITLE
Geo Location / setCenter on add form doesn't seem to work

### ISSUE THREAD

**Issue by stringfellow** [openwater/h2o-really#20]
it zooms but does not move

**Comment by stringfellow** [comment]
see add-obs-basics branch

**Comment by stringfellow** [comment]
might end up replacing floppy forms with django-leaflet - need to figure out how to interact with map once it has been initialised (no global var to work with) - see feature/map-widget

**Comment by jimr** [comment]
We're going to have to switch to a 1.6 pre-release for django-leaflet to work:

https://github.com/makinacorpus/django-leaflet#leaflet-map-forms-widgets

**Comment by jimr** [comment]
Ah, I see you've updated requirements, never mind.
