### ISSUE TITLE
Add me as a contributor

### ISSUE THREAD

**Issue by jimr** [openwater/h2o-really#25]
Would be good to be able to assign issues to me so you know what I'm working on. Have you considered setting up an H2O Really organisation? Once my field kit arrives, there might be some hacking to do on the software to have it submit readings & that won't fit in this project...

**Comment by stringfellow** [comment]
Sounds like a plan

**Comment by stringfellow** [comment]
Have asked GH to un-squat the username 'openwater'. This repo will become 'h2o-really'.

**Comment by jimr** [comment]
Ace, ta.
