### ISSUE TITLE
Static for datetime widget not being collected

### ISSUE THREAD

**Issue by stringfellow** [openwater/h2o-really#29]

**Comment by jimr** [comment]
It is, it just isn't prefixed with `datetimewidget`:

```
% find static -name \*datetime\*
static/css/datetimepicker.css 
static/js/bootstrap-datetimepicker.js
```

**Comment by stringfellow** [comment]
harp! it was a bug on master datetime widget - i fixed it last night in my fork (forgot to close) and it was already fixed on develop.
