### ISSUE TITLE
Download data buttons on map page, CSV and SHP

### ISSUE THREAD

**Issue by stringfellow** [openwater/h2o-really#37]
Should be able to download the data showing on the map, in CSV and Esri SHP format. Maybe also KML?

**Comment by stringfellow** [comment]
I have a fork (or maybe it got incorporated) of django-shapes that allows you to exclude sensitive fields (like email addresses)… might be useful here.

**Comment by jimr** [comment]
My fork of your fork has some other improvements too: https://bitbucket.org/jimr/django-shapes

**Comment by stringfellow** [comment]
This is pretty much there. Could use some refinement, but is functional
