### ISSUE TITLE
Add an API

### ISSUE THREAD

**Issue by stringfellow** [openwater/h2o-really#4]
API for Measurements, should exclude observer email address, and convert hstore values into JSON.

**Comment by jimr** [comment]
Don't want to add unnecessary noise, but I can highly recommend Django Rest Framework for stupidly simple API building. Awesome docs too.

**Comment by stringfellow** [comment]
Ooh! Nice. 

http://stackoverflow.com/questions/7303313/what-are-the-differences-between-django-tastypie-and-djangorestframework

I'm not fussy, so long as it can exclude private fields! I like the idea of browseable API, DTP doesn't quite achieve that out of the box.

**Comment by jimr** [comment]
Aye, you can add / remove / customise as much as you like. It also has a bunch of useful generic CBVs for CRUD (including adding M2M relationships, which blew my mind a little bit).

**Comment by jimr** [comment]
There you go, have an API :) You'll need to `pip install -r requirements.txt` to get Django Rest Framework installed.
